spring.application.name=fundvita
server.port=8081
server.servlet.context-path=/fundvita
frontend.url=${FRONTEND_URL}

#DB config
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

#solr
spring.data.solr.host=http://localhost:8983/solr/
spring.data.solr.repositories.enabled=false

# Google OAuth2 Registration
spring.security.oauth2.client.registration.google.client-id=830141585132-qkuqagmqgq90fkgveab0j1khius1hkck.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/fundvita/login/oauth2/code/google

# OAuth2 Scopes
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# Google Provider
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com

# Logging
logging.level.org.springframework.security.oauth2=DEBUG